kubevirt/vm-console-proxy

- automation/e2e-functests/deploy-kubevirt.sh
Added seccomp configuration to Kubevirt CR, that is needed by 4.13.
```release-note
None
```
> fix: Update Kubevirt CR used by CI

- README.md
- example-client/README.md
- Added installation instructions.
- Added note into example-client documentation to remind the user that browser needs to trust the TLS certificate from the cluster.
```release-note
None
```
> doc: Update documentation

- tests/proxy_test.go
- Tests use VMs with generated names, and so they don't need to wait until the previous VM is deleted.
- Increased timeout for `Eventually()` statements.
```release-note
None
```
> fix: Improve functional tests

- pkg/console/console.go
- pkg/console/tlsconfig/tlsconfig.go
- pkg/console/tlsconfig/tlsconfig_test.go
- pkg/filewatch/filewatch.go
- pkg/filewatch/filewatch_test.go
- tests/tlsconfig_test.go
When watching a file, the watch ends when it is deleted, and there is no way to restart it.
```release-note
None
```
> fix: watch directory instead of specific files

- manifests/deployment.yaml
The certificates are not needed, because the pod no longer connects directly to virt-handler.
```release-note
None
```
> fix: Do not mount virt-handler certificates to pod

- api/v1alpha1/constants.go
- go.mod
- manifests/api_service.yaml
- manifests/kustomization.yaml.in
- manifests/role_binding.yaml
- manifests/transformer_namespace.yaml
- pkg/console/authConfig/authConfig.go
- pkg/console/authConfig/authConfig_test.go
- pkg/console/authConfig/fake/fake.go
- pkg/console/console.go
- pkg/console/service/service.go
- pkg/console/service/service_test.go
- pkg/console/tlsconfig/tlsconfig.go
- pkg/console/tlsconfig/tlsconfig_test.go
- tests/proxy_test.go
- tests/tests_suite_test.go
- tests/tlsconfig_test.go
- vendor/k8s.io/client-go/tools/cache/testing/fake_controller_source.go
- vendor/modules.txt
**This PR is still a work in progress**
Fixes part of #20 
Jira: https://issues.redhat.com/browse/CNV-31169
```release-note
The /token endpoint is exposed as a kubernetes API extension
```
> feat: Expose /token endpoint as API extension

- README.md
- docs/api.md
Change documentation to reflect current API.
```release-note
Change documentation to reflect current API.
```
> chore: Update docs to reflect current API

- docs/api.md
Added more information about the `duration` parameter.
```release-note
None
```
> docs: Add information about "duration" API parameter

- docs/api.md
Added a short explanation of Kubernetes authentication method to API doc.
```release-note
None
```
> docs: Add information about authentication

- README.md
Change the link to a new asciinema demo.
```release-note
None
```
> docs: Change link to new asciinema demo

- manifests/kustomization.yaml.in
- manifests/user_role.yaml
- tests/user-role_test.go
The new Role `token.kubevirt.io:generate` will be installed in the cluster, and can be bound to user accounts to access the endpoint that generates tokens.
Fixes #36 
```release-note
Added role "token.kubevirt.io:generate" for users to access token generation endpoint.
```
> feat: Add a Role that will be used by users

- README.md
- docs/api.md
- Mentions the `ClusterRole` that can give users access to the API.
- Added an example `kubectl` command to delete `ServiceAccount` and revoke tokens.
Related: https://issues.redhat.com/browse/CNV-38641
```release-note
Improved API documentation.
```
> docs: Improve API documentation

- pkg/console/service/service.go
- tests/proxy_test.go
Fix incorrect `ownerReferences`. Now the resources will be correctly cleaned up after the VM is deleted.
Fixes: https://issues.redhat.com/browse/CNV-38845
```release-note
None
```
> fix: Fix owner references in created resources

- go.mod
The tag for `kubevirt.io/client-go` was created.
```release-note
None
```
> chore: Remove irrelevant comment

- README.md
Added an example `kubectl` command showing how to bind the `token.kubevirt.io:generate` `ClusterRole` to a user or `ServiceAccount`.
```release-note
None
```
> docs: Add example command how to bind ClusterRole

- pkg/console/service/service.go
- tests/proxy_test.go
Manual cherry-pick of: https://github.com/kubevirt/vm-console-proxy/pull/101
The manual change is in the test code, so that it compiles with older `gomega` and `kubevirt.io/client-go`.
```release-note
None
```
> [release-v0.4] fix: Fix owner references in created resources

- README.md
This saves time for new developers when onboarding to the project
Fixes #152 
**Special notes for your reviewer**:
```release-note NONE
```
> doc: enhance the README.md to include development instructions.

- Makefile
**What this PR does / why we need it**: enable KUBECONFIG default for functest
Fixes #
**Special notes for your reviewer**:
```release-note NONE
```
> fix: enable KUBECONFIG default for functest

- Dockerfile
- Makefile
This feature utilizes cross-compiling to generate binary files for the amd64 and s390x architectures, followed by the creation of images for both architectures.
**What this PR does / why we need it**: multiarch images enablement
Fixes #
**Special notes for your reviewer**:
```release-note NONE
```
> feat: build multi-architecture images in by default

- Dockerfile
- api/go.mod
- go.mod
- renovate.json
- vendor/modules.txt
Updated golang version to 1.23.2
```release-note
None
```
> chore: Update golang version to 1.23.2

- renovate.json
fix: regex in renovate config
previous regex caused Renovate to evaluate branches created by renovate as matching. To fix this, the ^ and $ are added to the regex.
```
NONE
```
> fix: regex in renovate config

- example-client/index.html
Kubevirt websocket endpoints expect different subprotocol than kubenetes endpoints.
Here is the definition of the subprotocol with documentation: https://github.com/kubevirt/kubevirt/blob/0acbdb417a0f7721fca9b73bd4be97391bd0ed54/staging/src/kubevirt.io/client-go/subresources/constants.go#L22-L25
```release-note
None
```
> fix: example-client: Change subprotocol to what kubevirt expects
